rd  /S /Q ".vs\C-HashAPI\v17\ipch"
del /S /Q ".vs\C-HashAPI\v17\Browse.VC.db"
del /S /Q ".vs\C-HashAPI\v17\Solution.VC.db"

rd /S /Q "Debug"
rd /S /Q "Release"
rd /S /Q "x64"
rd /S /Q "x86"

rd /S /Q "example\win_exec\Debug"
rd /S /Q "example\win_exec\Release"
rd /S /Q "example\win_exec\x64"
rd /S /Q "example\win_exec\x86"
rd /S /Q "example\find_mod\Debug"
rd /S /Q "example\find_mod\Release"
rd /S /Q "example\find_mod\x64"
rd /S /Q "example\find_mod\x86"

rd /S /Q "test\Debug"
rd /S /Q "test\Release"
rd /S /Q "test\x64"
rd /S /Q "test\x86"